### ISSUE TITLE
Support for v1beta1 API version from v0.5.0 of ESO

### ISSUE THREAD

**Issue by skikkh** [external-secrets/kes-to-eso#4]
2022-04-05, release v0.5.0 of ESO: https://github.com/external-secrets/external-secrets/releases/tag/v0.5.0

v1alpha1 has been deprecated since v0.5.0. How do you plan to proceed to address this issue?

**Comment by gusfcarvalho** [comment]
Hi @skikkh! Yes, I think we need to update it some time soon. As for now, I don't believe this should cause any issues as `v1alpha` is still accepted.

**Comment by mchiao-bigw** [comment]
Hi @gusfcarvalho is there a timeline for v1beta1 support? Thanks in advance!

**Comment by emily-zall** [comment]
when I was using v1alpha1 I got the following error intermittently: `externalSecret/terraform/workspacesecrets dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version [external-secrets.io/v1alpha1](http://external-secrets.io/v1alpha1): conversion webho │
│ ok for [external-secrets.io/v1beta1](http://external-secrets.io/v1beta1), Kind=ExternalSecret returned invalid metadata: invalid metadata of type <nil> in input object`

it was resolved by updating to v1beta1

**Comment by aberenshtein** [comment]
Any updates here?
